version: '2'

services:
  web:
    image: php:8.0-apache
    volumes:
      - .:/var/www/html
    links:
      - db
    ports:
      - "80:80"
  db:
    image: mysql:5
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=hamstersbooks
     - MYSQL_USER=hamstersbooks
     - MYSQL_PASSWORD=hamstersbooks
   ports:
    - "3306:3306"

volumes:
  mysql-data:
