name: "🐹 Hamsters Books CI/CD Pipeline"
on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 
      - name: build
        run: |
          make release
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy
        run: |
          echo "deploying"

  